"""initial_schema_with_all_tables

Revision ID: 4896404f4fba
Revises: 
Create Date: 2025-10-29 23:56:13.006664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4896404f4fba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Criar extensões do PostgreSQL
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('extensao', sa.String(length=10), nullable=False),
    sa.Column('chave_storage', sa.String(length=500), nullable=False),
    sa.Column('hash_checksum', sa.String(length=64), nullable=False),
    sa.Column('data_upload', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('tamanho_bytes > 0', name='tamanho_valido'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_storage'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('enderecos',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('pais', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("cep ~ '^\\d{8}$'", name='cep_valido'),
    sa.CheckConstraint('LENGTH(estado) = 2', name='uf_valida'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name='latitude_valida'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name='longitude_valida'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tentativas_login', sa.SmallInteger(), nullable=False),
    sa.Column('bloqueado_ate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("cpf ~ '^\\d{11}$'", name='cpf_valido'),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='email_valido'),
    sa.CheckConstraint('tentativas_login >= 0 AND tentativas_login <= 5', name='tentativas_validas'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('denuncias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('endereco_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_ANALISE', 'EM_FISCALIZACAO', 'CONCLUIDA', 'ARQUIVADA', 'CANCELADA', name='status_denuncia'), nullable=False),
    sa.Column('categoria', sa.Enum('AMBIENTAL', 'SANITARIA', 'CONSTRUCAO_IRREGULAR', 'POLUICAO_SONORA', 'OUTROS', name='categoria_denuncia'), nullable=False),
    sa.Column('prioridade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridade'), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endereco_id'], ['enderecos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('grupo_role',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_id', 'role_id')
    )
    op.create_table('usuario_grupo',
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'grupo_id')
    )
    op.create_table('arquivos_denuncia',
    sa.Column('arquivo_id', sa.BigInteger(), nullable=False),
    sa.Column('denuncia_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('arquivo_id', 'denuncia_id')
    )
    op.create_table('fiscalizacoes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('denuncia_id', sa.BigInteger(), nullable=False),
    sa.Column('fiscal_id', sa.BigInteger(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('AGUARDANDO', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='status_fiscalizacao'), nullable=False),
    sa.Column('data_inicializacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('data_conclusao IS NULL OR data_conclusao >= data_inicializacao', name='datas_validas'),
    sa.ForeignKeyConstraint(['denuncia_id'], ['denuncias.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fiscal_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('analises',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('fiscalizacao_id', sa.BigInteger(), nullable=False),
    sa.Column('tipo_analise', sa.Enum('IMAGEM', 'TEXTO', 'RELATORIO', 'VIDEO', name='tipo_analise'), nullable=False),
    sa.Column('dados_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resultado_principal', sa.Text(), nullable=True),
    sa.Column('confianca', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('processado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confianca IS NULL OR (confianca >= 0 AND confianca <= 100)', name='confianca_valida'),
    sa.ForeignKeyConstraint(['fiscalizacao_id'], ['fiscalizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('arquivos_fiscalizacao',
    sa.Column('arquivo_id', sa.BigInteger(), nullable=False),
    sa.Column('fiscalizacao_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fiscalizacao_id'], ['fiscalizacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('arquivo_id', 'fiscalizacao_id')
    )
    op.create_table('arquivos_analise',
    sa.Column('arquivo_id', sa.BigInteger(), nullable=False),
    sa.Column('analise_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analise_id'], ['analises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('arquivo_id', 'analise_id')
    )
    # ### end Alembic commands ###

    # Criar índices de performance
    # Usuários
    op.create_index('idx_usuarios_cpf', 'usuarios', ['cpf'], postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_usuarios_email', 'usuarios', ['email'], postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_usuarios_ativo', 'usuarios', ['ativo'], postgresql_where=sa.text('deleted_at IS NULL'))

    # Denúncias
    op.create_index('idx_denuncias_usuario', 'denuncias', ['usuario_id'])
    op.create_index('idx_denuncias_endereco', 'denuncias', ['endereco_id'])
    op.create_index('idx_denuncias_status', 'denuncias', ['status'])
    op.create_index('idx_denuncias_categoria', 'denuncias', ['categoria'])
    op.create_index('idx_denuncias_created', 'denuncias', [sa.text('created_at DESC')])

    # Fiscalizações
    op.create_index('idx_fiscalizacoes_denuncia', 'fiscalizacoes', ['denuncia_id'])
    op.create_index('idx_fiscalizacoes_fiscal', 'fiscalizacoes', ['fiscal_id'])
    op.create_index('idx_fiscalizacoes_status', 'fiscalizacoes', ['status'])
    op.create_index('idx_fiscalizacoes_codigo', 'fiscalizacoes', ['codigo'])

    # Análises
    op.create_index('idx_analises_fiscalizacao', 'analises', ['fiscalizacao_id'])
    op.create_index('idx_analises_tipo', 'analises', ['tipo_analise'])
    op.create_index('idx_analises_dados_gin', 'analises', ['dados_json'], postgresql_using='gin')

    # Endereços
    op.create_index('idx_enderecos_cep', 'enderecos', ['cep'])
    op.create_index('idx_enderecos_cidade_estado', 'enderecos', ['cidade', 'estado'])
    op.create_index('idx_enderecos_coordenadas', 'enderecos', ['latitude', 'longitude'],
                   postgresql_where=sa.text('latitude IS NOT NULL AND longitude IS NOT NULL'))

    # Arquivos
    op.create_index('idx_arquivos_hash', 'arquivos', ['hash_checksum'])
    op.create_index('idx_arquivos_upload', 'arquivos', [sa.text('data_upload DESC')])

    # Criar função e triggers para atualizar updated_at
    op.execute("""
        CREATE OR REPLACE FUNCTION atualizar_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Triggers para cada tabela
    for table in ['usuarios', 'grupos', 'roles', 'enderecos', 'denuncias', 'fiscalizacoes', 'analises', 'arquivos']:
        op.execute(f"""
            CREATE TRIGGER trigger_{table}_updated_at
            BEFORE UPDATE ON {table}
            FOR EACH ROW
            EXECUTE FUNCTION atualizar_updated_at();
        """)

    # Inserir dados iniciais (seed)
    # Grupos padrão
    op.execute("""
        INSERT INTO grupos (uuid, nome, descricao, ativo, created_at, updated_at) VALUES
            (uuid_generate_v4(), 'Administradores', 'Acesso total ao sistema', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            (uuid_generate_v4(), 'Fiscais', 'Responsáveis por fiscalizações', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            (uuid_generate_v4(), 'Cidadãos', 'Usuários que podem fazer denúncias', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    """)

    # Roles padrão
    op.execute("""
        INSERT INTO roles (uuid, nome, descricao, ativo, created_at, updated_at) VALUES
            (uuid_generate_v4(), 'admin', 'Administração completa', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            (uuid_generate_v4(), 'fiscalizar', 'Criar e gerenciar fiscalizações', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            (uuid_generate_v4(), 'denunciar', 'Criar denúncias', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            (uuid_generate_v4(), 'visualizar_denuncias', 'Visualizar denúncias', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
            (uuid_generate_v4(), 'gerenciar_usuarios', 'Gerenciar usuários do sistema', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    """)

    # Relacionamento Grupo-Role padrão
    op.execute("""
        INSERT INTO grupo_role (grupo_id, role_id, created_at)
        SELECT g.id, r.id, CURRENT_TIMESTAMP FROM grupos g, roles r WHERE g.nome = 'Administradores';
    """)

    op.execute("""
        INSERT INTO grupo_role (grupo_id, role_id, created_at)
        SELECT g.id, r.id, CURRENT_TIMESTAMP FROM grupos g, roles r 
        WHERE g.nome = 'Fiscais' AND r.nome IN ('fiscalizar', 'visualizar_denuncias');
    """)

    op.execute("""
        INSERT INTO grupo_role (grupo_id, role_id, created_at)
        SELECT g.id, r.id, CURRENT_TIMESTAMP FROM grupos g, roles r 
        WHERE g.nome = 'Cidadãos' AND r.nome IN ('denunciar', 'visualizar_denuncias');
    """)

    # Adicionar comentários nas tabelas
    op.execute("COMMENT ON TABLE usuarios IS 'Usuários do sistema com autenticação e controle de acesso'")
    op.execute("COMMENT ON TABLE grupos IS 'Grupos de usuários para controle de permissões'")
    op.execute("COMMENT ON TABLE roles IS 'Papéis/permissões que podem ser atribuídos a grupos'")
    op.execute("COMMENT ON TABLE denuncias IS 'Denúncias realizadas por cidadãos'")
    op.execute("COMMENT ON TABLE fiscalizacoes IS 'Fiscalizações realizadas em resposta às denúncias'")
    op.execute("COMMENT ON TABLE analises IS 'Análises de IA (visão computacional) sobre fiscalizações'")
    op.execute("COMMENT ON TABLE arquivos IS 'Arquivos anexados (imagens, documentos, etc)'")
    op.execute("COMMENT ON TABLE enderecos IS 'Endereços das denúncias'")

    op.execute("COMMENT ON COLUMN usuarios.bloqueado_ate IS 'Data até quando o usuário está bloqueado por tentativas de login'")
    op.execute("COMMENT ON COLUMN analises.confianca IS 'Nível de confiança da análise de IA (0-100%)'")
    op.execute("COMMENT ON COLUMN arquivos.hash_checksum IS 'SHA-256 do arquivo para verificação de integridade'")
    op.execute("COMMENT ON COLUMN fiscalizacoes.codigo IS 'Código único de protocolo da fiscalização'")


def downgrade() -> None:
    # Remover índices
    op.drop_index('idx_arquivos_upload', 'arquivos')
    op.drop_index('idx_arquivos_hash', 'arquivos')
    op.drop_index('idx_enderecos_coordenadas', 'enderecos')
    op.drop_index('idx_enderecos_cidade_estado', 'enderecos')
    op.drop_index('idx_enderecos_cep', 'enderecos')
    op.drop_index('idx_analises_dados_gin', 'analises')
    op.drop_index('idx_analises_tipo', 'analises')
    op.drop_index('idx_analises_fiscalizacao', 'analises')
    op.drop_index('idx_fiscalizacoes_codigo', 'fiscalizacoes')
    op.drop_index('idx_fiscalizacoes_status', 'fiscalizacoes')
    op.drop_index('idx_fiscalizacoes_fiscal', 'fiscalizacoes')
    op.drop_index('idx_fiscalizacoes_denuncia', 'fiscalizacoes')
    op.drop_index('idx_denuncias_created', 'denuncias')
    op.drop_index('idx_denuncias_categoria', 'denuncias')
    op.drop_index('idx_denuncias_status', 'denuncias')
    op.drop_index('idx_denuncias_endereco', 'denuncias')
    op.drop_index('idx_denuncias_usuario', 'denuncias')
    op.drop_index('idx_usuarios_ativo', 'usuarios')
    op.drop_index('idx_usuarios_email', 'usuarios')
    op.drop_index('idx_usuarios_cpf', 'usuarios')

    # Remover triggers
    for table in ['usuarios', 'grupos', 'roles', 'enderecos', 'denuncias', 'fiscalizacoes', 'analises', 'arquivos']:
        op.execute(f'DROP TRIGGER IF EXISTS trigger_{table}_updated_at ON {table}')

    # Remover função
    op.execute('DROP FUNCTION IF EXISTS atualizar_updated_at()')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arquivos_analise')
    op.drop_table('arquivos_fiscalizacao')
    op.drop_table('analises')
    op.drop_table('fiscalizacoes')
    op.drop_table('arquivos_denuncia')
    op.drop_table('usuario_grupo')
    op.drop_table('grupo_role')
    op.drop_table('denuncias')
    op.drop_table('usuarios')
    op.drop_table('roles')
    op.drop_table('grupos')
    op.drop_table('enderecos')
    op.drop_table('arquivos')
    # ### end Alembic commands ###

    # Remover extensões (opcional - comente se outras aplicações usam)
    # op.execute('DROP EXTENSION IF EXISTS "pgcrypto"')
    # op.execute('DROP EXTENSION IF EXISTS "uuid-ossp"')

